"""Created Question model

Revision ID: 76872191b521
Revises: 
Create Date: 2021-09-25 11:08:25.726002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76872191b521'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('name', name='users_name_key')
    )
    # ### end Alembic commands ###
